## Last commit: 2026-09-20 10:14:03 IST by netops
version 20.4R3.8;
system {
    host-name srx-branch-07;
    time-zone Asia/Kolkata;
    root-authentication {
        encrypted-password "$6$FAKEsalt$FAKEhashFAKEhashFAKEhash"; ## SECRET-DATA
    }
    login {
        message "Authorized access only. Activity is monitored.";
        class noc-ops {
            idle-timeout 30;
            permissions [ view configure ];
        }
        user netops {
            class super-user;
            authentication {
                encrypted-password "$6$FAKEsalt2$FAKEhash2FAKEhash2"; ## SECRET-DATA
            }
        }
    }
    services {
        ssh {
            protocol-version v2;
        }
        telnet;
        web-management {
            http {
                interface ge-0/0/1.0;
            }
        }
    }
    syslog {
        host 10.20.0.15 {
            any notice;
        }
        file messages {
            any notice;
        }
    }
    ntp {
        server 10.20.0.1;
    }
}
interfaces {
    ge-0/0/0 {
        description "WAN uplink to ISP";
        unit 0 {
            family inet {
                address 203.0.113.10/30;
            }
        }
    }
    ge-0/0/1 {
        unit 0 {
            family inet {
                address 192.168.10.1/24;
            }
        }
    }
}
snmp {
    community public {
        authorization read-only;
    }
}
routing-options {
    static {
        route 0.0.0.0/0 next-hop 203.0.113.9;
    }
}
