#config-version=FGT60F-7.2.5-FW-build1517-230606:opmode=0:vdom=0:user=admin
#conf_file_ver=187263511247836
#buildno=1517
#global_vdom=1
config system global
    set admintimeout 480
    set alias "FGT60F-EDGE"
    set hostname "fgt-edge-08"
    set timezone "Asia/Kolkata"
    set admin-telnet enable
end
config system interface
    edit "wan1"
        set vdom "root"
        set ip 198.51.100.20 255.255.255.252
        set allowaccess ping https ssh telnet http
        set description "ISP uplink"
    next
    edit "internal"
        set vdom "root"
        set ip 192.168.1.99 255.255.255.0
        set allowaccess ping https ssh
    next
end
config system admin
    edit "admin"
        set accprofile "super_admin"
        set password ENC SH2FAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKE
    next
end
config system snmp community
    edit 1
        set name "public"
    next
end
config log syslogd setting
    set status enable
    set server "10.30.0.25"
end
config vpn ipsec phase1-interface
    edit "to-hq"
        set interface "wan1"
        set psksecret ENC FAKEPSKFAKEPSKFAKEPSK
    next
end
config firewall policy
    edit 1
        set name "wan-to-lan-any"
        set srcintf "wan1"
        set dstintf "internal"
        set srcaddr "all"
        set dstaddr "all"
        set action accept
        set schedule "always"
        set service "ALL"
    next
    edit 2
        set name "block-telnet"
        set srcintf "wan1"
        set dstintf "internal"
        set srcaddr "all"
        set dstaddr "all"
        set action deny
        set schedule "always"
        set service "TELNET"
        set logtraffic all
    next
end
config router static
    edit 1
        set gateway 198.51.100.21
        set device "wan1"
    next
end
